### ISSUE TITLE
Give more control in elastic index configuration

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#1003]
## Problem to Solve

Today OpenCTI create simple index to manage the data but not directly customizable by the admin user. It prevent the usage of rollhover index (https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html) 

## Current Workaround

Manage the indices after creation through direct elastic commands? not sure is always possible

## Proposed Solution

Find a way to configure the platform to create the expected indices configuration

**Comment by dmille6** [comment]
i have limited knowledge of elasticsearch.. but i'm learning the hard way. 

from what i can see in the current openCTI -> elasticsearch configuration is that openCTI is saving to multiple static/predefined indexes. This will work fine for small databases.. or small amounts of data.. but when those indexes reach 40-60gb. There will be performance issues. I also dont see any way to manage old data. 40-60gb seems like a lot.. but i'm running a honeynet of multiple honeypots submitting data to openCTI. i can easily add 200k in indicators a day. 40-60gb will be 20-40days at my current rate of ingestion. 

What i suggest:
on initial install/setup:
- create elasticsearch index defintiions (define fields and field types)
- create aliases for index types. instead of writing directly to a hard coded index, you write to an alias. This allows ES to manage the indexes and data. 
- create index lifecycle policies and roll over policies to manage the data. 
     example: roll over to a new index when the index reaches 40gb in size
   If its set up this way, a user can modify the policies to better fit the needs of the user.  
Example: these policies also allow you to manage where/how the data is stored. 
     example: for the initial 90 days store data on SSD nodes of the elastic cluster (hot nodes) after 90 days move data to slower/cheaper HDD nodes of the elastic cluster (warm nodes) then after 3 yrs delete data.

**Comment by richard-julien** [comment]
Hi @dmille6,

Thanks for your message.
I just committed in order to "at platform creation"
* Create elasticsearch needed indices. (for example opencti_stix_core_relationships-000001)
* Create aliases for each index (opencti_stix_core_relationships)

With this default configuration it will be simple for everyone to apply its own lifecycle strategy manually or automatically with something like https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html.

For existing platform you will have to do it by yourself. 
1. Stop the platform
2. Cloning the current indices to create the new name INDEX-000001
3. Add the correct alias inside each index.
4. Restart the platform
5. Configure your rolling strategy.

Sounds good for you?

**Comment by richard-julien** [comment]
After some extra research looks like my implementation is not complete.
I need to continue and do some testing around the rollout, and the come back to you with more info

**Comment by richard-julien** [comment]
Hi @dmille6 ,

I finally have a first implementation that validate my previous message.
This is true for all index of the platform be just documented here an example with index opencti_stix_core_relationships.

For the index "opencti_stix_core_relationships"
- At platform init, index opencti_stix_core_relationships-00001 will be created
  For writing: An alias opencti_stix_core_relationships is created targeting opencti_stix_core_relationships-00001
  For reading: OpenCTI will used a wildcard pattern like this: opencti_stix_core_relationships*
  (Suffix and options to allow read from frozen index will be added in the platform configuration)

For existing platform you will have to do it by yourself. (clone, create alias, ...)
I tried with success to rollout different indices with different strategy.
I hope this approach will cover your needs.
