### ISSUE TITLE
OpenCTI dashboard is all blank

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1005]
## Description

After successful install, I added MISP collector. (I have my MISP running successfully on another server)

The dashboard is all blank. Any reason why? And where do I start looking if there are issues of why I don't see any MISP data in the opencti dashboard?

## Environment

1. OS is Ubuntu 20 on Proxmox HomeLabs
2. OpenCTI latest version

**Comment by richard-julien** [comment]
Hi @NetEyes ,

Its a bit difficult to help you.
Do you check the status of the connector? the docker logs the connector?
The connector is visible inside the OpenCTI UI? Do you see some messages in the queue?
Do you have started some workers?

**Comment by NetEyes** [comment]
I download the connector MISP.  
Configured the docker-compose.yml 
run the docker compose
the 'misp' is showing in the OpenCTI UI.

"Do you see some messages in the queue?" - I don't know how to check the messages in the queue, please provide steps -by step.
"Do you have started some worker" - I don't know how to do that. Where is the tutorial?

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity, I think the recent blog post around [OpenCTI performances](https://medium.com/luatix/opencti-platform-performances-e3431b03f822) will help you to better understand the messages in the queue and the workers roles. This article contains a lot of screenshots and ways to answer your 2 questions.
