### ISSUE TITLE
Make Observables immutable, per STIX specification

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1081]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

The STIX specification (per my interpretation) says that SCOs should not be able to be changed.
From Section 3.6: "a SCO cannot be versioned unless custom properties (discussed in section 11.1) are used."
I believe this was implemented in OpenCTI 3.x, but no longer in OpenCTI 4.2.1

## Current Workaround

Tell users not to change observables

## Proposed Solution

Make observables immutable, as they were in OpenCTI 3.x

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Since we're using custom properties such as the `x_opencti_description` or the `x_opencti_score`, we've chosen to let observables mutable. To be honest, updating an observable MD5 which has only a SHA-1 previously is a great use case! And if analysts are marking mistakes, they can fix their observable. It's not optimal we know but this is something we would like to keep, at least for the moment.

Kind regards,
Samuel
