### ISSUE TITLE
Create Read/Write Permissions for Marking Definitions

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1097]
## Problem to Solve

A team using custom marking definitions will only want its users to attach these marking definitions to objects they create. However, intelligence ingested from 3rd party sources may use other marking definitions, like TLP. 

There should be a way to specify that users in a group can view objects with marking definitions, but only use a subset of the marking definitionis when creating objects

## Current Workaround

Currently, OpenCTI has a bug that allows all users to view all marking definitions. I suspect this will be fixed soon, at which point this feature will become important. 

## Proposed Solution

There should be a way to specify that users in a group can view objects with marking definitions, but only use a subset of the marking definitionis when creating objects.
For example, when deciding a group marking definition permissions, instead of one checkbox per marking definition - two columns of checkboxes - one to "view" and one to "use"

**Comment by richard-julien** [comment]
Hi @securitiz , not sure to understand your point.
Today view and assign is related to the same restriction. So a user will be able to assign a marking only if he is able to use it.
I think we add this restriction in the UI but maybe we forget to enforce this fact in the API... I need to check that.

I think splitting the 2 concerns could create inconsistency. If a user have the right to assign but not view he will be able to create but not view/edit anymore just after creation.

**Comment by securitiz** [comment]
I agree that users having the right to assign but not view would be strange and doesn't make sense. Perhaps if a user has rights to assign a marking definition, the checkbox (as I imagine it) for view rights would automatically be checked.
I do think it makes sense to allow users to view certain marking definitions, but not create them. For example, if an org creates its own marking definitions, but is ingesting data that uses TLP definitions - we want users to be able to see the ingested data, but not be allowed to assign TLP marking definitions to objects they create..

**Comment by richard-julien** [comment]
Thanks for your message, i have a better understanding of your remarks now.
So yes we have 2 problems to solve.

1. Check at creation if user have the right to assign this marking. If not -> reject

2. Assign marking directly to the user. 
A connector without the bypass capability could have some trouble to use marking definition created by himself. 
That could be mitigated by adding marking directly on the user instead of the group. If a connector/user create a marking, the system will auto assign this marking directly to the user responsible of the creation.

3. Have the capability to people to see marking but not assign it.
Make sens to have marking setup only through connector and not user. For this like your proposal we need to split the assign/view with the inner behavior that if you have the capa to write you have indeed the capa to see.
Add new capability in knowledge -> modify marking definitions.

**Comment by securitiz** [comment]
Yes, this makes sense!

**Comment by SamuelHassine** [comment]
Hello,

We've to review the priority of this feature. #1449 should be enough to avoid any problem in the future. Be sure to allow groups to automatically be authorized to some groups.

**Comment by SamuelHassine** [comment]
Since we have added the option:

![image](https://user-images.githubusercontent.com/1334279/142754893-f1c09747-327c-4c37-83ee-b68d5613e163.png)

No problem has been reported anymore. I think this option is enough to be able to create a group for connectors with this option enabled. In this case, it's easy for deny this group from accessing to sensible data (uncheck TLP:RED) but automatically authorize new ones (such as "FireEye" or MITRE Copyright).

Therefore I'm closing this issue. Please open a new one if you still have any problem with this describing a use case where the group option could not be used.
