### ISSUE TITLE
Docker-compose doesn't work

### ISSUE THREAD

**Issue by seifreed** [OpenCTI-Platform/opencti#114]
## Description

I just did docker-compose up and I can't get up the environment:

## Environment

1. Ubuntu 18
2. Last version

## Reproducible Steps

git clone opencti

`docker-compose up`

## Expected Output

```
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
openctidocker_elasticsearch_1 exited with code 1
opencti_1        | elasticsearch: forward host lookup failed: Unknown host
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | elasticsearch: forward host lookup failed: Unknown host
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | elasticsearch: forward host lookup failed: Unknown host
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for token in shared config...
```

**Comment by SamuelHassine** [comment]
Hello,

The problem come from `openctidocker_elasticsearch_1 exited with code 1`. Could you check why the ElasticSearch Docker container is exiting?

**Comment by seifreed** [comment]
Yup, I saw that the thing is. Did you guys try to spin up opencti on a clean ubuntu 18?
Before start to troubleshooting it myself, I wanna know which versions are compatible and if it's work by default ^_^!

**Comment by cdiraimondi** [comment]
I've had problems similar in the past due to the the docker-compose.yml containing options for volumes in order to make the data persistent. I resorted back to the previous version of docker-compose.yml which did not have the volumes configuration. Are you noticing any exceptions being thrown by ElasticSearch?

**Comment by soreno123** [comment]
Same problem here, where i can find the previous version of docker-compose.yml ?
Anyway i'm getting also this exception:
elasticsearch_1  | [2019-07-04T12:24:50,509][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      ... 6 more

**Comment by SamuelHassine** [comment]
Hello there,

We refactor the volumes configuration of Docker compose. We come back to a more classic configuration compliant with most of cloud platforms.

Could you please clear all your config (stop Docker daemon, rm -R /var/lib/docker/*, start Docker daemon) and start fresh (git pull this repository and docker-compose up) ?

**Comment by soreno123** [comment]
Hello @SamuelHassine, i followed your advice and now is working, i can correctly login in the platform.
Thanks!

**Comment by SamuelHassine** [comment]
@soreno123 : Yes sorry, we are aware of this bug #118.
