### ISSUE TITLE
Tag hierarchy 

### ISSUE THREAD

**Issue by nearkella** [OpenCTI-Platform/opencti#1140]
## Problem to Solve

{ Is it possible to have hierarchy in the tags/}

## Current Workaround

{I don't. They're all in the same level.}

## Proposed Solution

{ Add sub-tags so that their will be relations and hierarchy between the tags }

## Additional Information

{ Nothing to add.}

**Comment by nino-filigran** [comment]
@nearkella we're going through our BL and tickets that have not been touched since a while.
Is it still a need?
I know this ticket has been raised since a while, but do you recall the problem you would solve by having a hierarchy of tags? What would it helps you achieve that you cannot do at the moment?

**Comment by nearkella** [comment]
You can close the ticket, thx

Near Robert Kella 石磊
eBay Cyber Crime Security
***@***.***
+972-533362644

[cid:6031dd55-4880-4e33-ae2a-cc7873ed8d53]
________________________________
