### ISSUE TITLE
Display additional object details when hovering over them in Knowledge Graph

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1143]
## Problem to Solve

When viewing objects in the knowledge graph, especially File observables, the user only sees the hash, which makes the objects difficult to differentiate.

If a user wants to view more information about an objects, they must click on the object and open a new page

## Current Workaround

Click on the object and open a new page.

## Proposed Solution

When hovering over an object, display additional information about the object. For example, when hovering over a File observable, one would see a box (similar to how one see dates when hovering over a relationship) with the file name, and other hashes.

Also, slightly related, I believe the File observable should display the file name, rather than the hash, in the knowledge graph. While hashes are unique, file names are more user-friendly. 

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Due to performances issues on large graph, we are not able to display "a lot" of information when hovering the nodes. But still, we've added the file name and the file hash when it's available. Please open other issues if you have other precise ideas/needs like this one! 

Kind regards,
Samuel
