### ISSUE TITLE
Automatically start connectors when upload a report

### ISSUE THREAD

**Issue by HugooB** [OpenCTI-Platform/opencti#1209]
## Problem to Solve

After report insertion into the platform, I manually have to click the button to let the import-file-pdf-observables extract all the IoCs. Can this process be started automatically or through some sort of API call?

## Current Workaround

Manually clicking the button

## Proposed Solution

import-file-pdf-observables starts as soon as report is uploaded or API call to start it

## Additional Information

none

**Comment by samjackson200** [comment]
Is there anyway this action can be made optional, with a per-connector specific setting? We have found that having the PDF observables extractor running automatically with every single report uploaded actually creates more harm than good due to the high number of incorrect observables extracted (e.g. when a part of a report is incorrectly seen as observable when it is infact just a part of the text of the report)
