### ISSUE TITLE
Missing descriptions in AttackPatterns

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#1318]
## Description

After several weekly updates of the AttackPatterns (MITRE connector autoupdate), there's an increasing number of entries without a description where there used to be one. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.2 LTS
2. OpenCTI version: OpenCTI 4.5.0
3. OpenCTI client: frontend
4. Other environment details: same behaviour on both native server install and VM

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run weekly MITRE update

## Expected Output

Description for every entry.

## Actual Output

see attached pic below
 
## Additional information
![octi](https://user-images.githubusercontent.com/75171233/116821235-5b888c00-ab79-11eb-8b06-43f36650196e.png)

**Comment by SamuelHassine** [comment]
Hello @s3ns0r1um,

These attack patterns have been "revoked" by the MITRE, the description has been deleted from the dataset.  

As you can see here: https://github.com/mitre/cti/blob/eb1b9385d44340ce867a77358c5f5aaed666e54c/enterprise-attack/attack-pattern/attack-pattern--c848fcf7-6b62-4bde-8216-b6c157d48da0.json, the "revoked" attack patterns do not have any description.

We are preparing a proper management of revoked entities in OpenCTI with the following options:

- pass them in read-only and prevent creation of relationships to revoked entities
- Ignore revoked=true/false at the connector level (to avoid ingest revoked entities)
- garbage collector based on customizable filter like entity_type=Observable and revoked since more than 1 month => delete
- hide by defailt all revoked entities and display a button to force display

Kind regards,
Samuel

**Comment by s3ns0r1um** [comment]
Definitely missed that one. Thank you for the explanation, Samuel!
