### ISSUE TITLE
Any queue for being expired IOC

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/opencti#1411]
## Problem to Solve

On OpenCTI we have queue for incoming IOC for adding adictional information. Do we have any queue for IOCs that being expired. 

I just think, each indicator has it own Valid From and Valid Until time (default 1 year) but we don't know what is the best time to live for each IOC. So if we have any chance to stream the expired IOC, we will have a connector that do something like checking it with other source if it back to clean so we can temporary ignore it, but it still a malicious one, we can extend the expiration date. 

## 
Thanks for looking at this.

**Comment by SamuelHassine** [comment]
Hello,

Since OpenCTI 5.3.0, the "Live Stream" provides you with an event when the indicator is "revoked" by the expiration manager. What you can do, is to create a live stream like this:

![image](https://user-images.githubusercontent.com/1334279/170953133-f7cda655-0ecf-4d27-95ef-b66a45d502df.png)

This mean the stream will notify you every time an indicator is revoked, with a "create event". If you then extend the valid_until date and the revoked returns to false, you will receive a "delete event".

If this covers your use case?

Kind regards,
Samuel
