### ISSUE TITLE
Multitenancy support

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#1477]
## Problem to Solve

TLDR: I don't have enough budget to run one OpenCTI instance per tenant.
 
I would like to run a single instance of OpenCTI where:

- I produce the intel
- I allow users to read the intel 
- I allow users to create new intel (reports/IOC/etc) without sharing it to others tenants.

## Current Workaround 

- Running a primary  instance of OpenCTI 
- Running a secondary instance of OpenCTI by tenant 
- Live stream the intel from the primary instance to each secondary instance 

## Proposed Solution

Implement a multitenant architecture.

**Comment by SamuelHassine** [comment]
Hello @2xyo @nor3th @richard-julien,

Since the version 5.0.0, it's now possible to launch multiple OpenCTI instances on the same stack (same Redis, Elastic, Minio, RabbitMQ) using new configuration parameters for prefixing databases.

```
redis:namespace
elasticsearch:index_prefix
minio:bucket_name
```

Since RabbitMQ creates queues based on IDs of connectors, no namespace is needed.

We consider this issues closed as we will not support "full" multi-tenancy in the near future and these enhancements ensure the capability to deploy multiple OpenCTI tenants on the same technical stack.

Kind regards,
Samuel
