### ISSUE TITLE
Can't add alias name to intrusion-set if the the alias name is the same as another existing intrusion-set

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1485]
## Problem to Solve

I can't add alias name to the intrusion-set if the the alias name is the same as another existing intrusion-set name. It will show "This update will produce a duplicate"

## Current Workaround

No workaround currently.

## Proposed Solution

It should support to add an alias name to intrusion-set, even the alias name is the same as the existing intrusion-set name.

## Additional Information
STEP 1. To created an intrusion-set (ex. ABC)
(ps. In OpenCTI, there is an existing intrusion-set named ex. DEF)
STEP 2. To add alias DEF to ABC, then it shows "This update will produce a duplicate"
![image](https://user-images.githubusercontent.com/10161931/127112739-f1065ffe-2b71-4952-9d3a-357afd801932.png)

**Comment by manonviallet** [comment]
Hello @tanyawang1218, it seems to me this feature might be a little dangerous, as it will generate conflicts : if you add automatically afterwards data with relationship to intrusion set "DEF", since there are two entities with this name or alias, there will be an error as the connector will not know to which object the data is related to. It may also create confusion for users.
Usually in OpenCTI, when two object have the same alias/name, it is considered the same and they would be merge. 

However, I understand your difficulty, has we also have on our side intrusion sets we want to keep separated but which have the same name publicly.
Have you considered as a workaround either adding more info in the alias (such as intrusion set DEF with alias "ABC (name of source)" which would make it different from the name of intrusion set "ABC" but still searchable) ; or adding this alias in the description of the intrusion set along with a short explanation of why both have the same name but are not the same object ?
In both case, the alias will pop up in search results anyway.

**Comment by richard-julien** [comment]
Just by curiosity, why it is required to keep the element splitted if they represent the same stuff?

**Comment by manonviallet** [comment]
@richard-julien a case we have usually is that for intrusion sets, each security researcher/team will document it using the name they gave it, and describing what they, personally, observed. In many cases, it work fine as what security researchers/teams observed is the same and add up. 

But in some cases, it is much more fuzzier and you have several intrusion sets which are distinct but have important overlaps : for instance, team 1 will describe a intrusion set A, but team 2 will say that they see two distinct intrusion sets, named B and C in what team 1 described as A, and that C also has other activities that are larger than just what is described in A (and maybe another team will say that it is intrusion set D...).

In that case, you may want to be able to track independently at least A and C, but give C as an alias the name of A or write in the description that it has some links to A.

Another case is if you don't trust/don't make the same observations on the technical level : if there is several malicious wave of activities and everyone says it is the same intrusion set but different campaigns, and you are not convinced by the technical proof given, so you want to keep track of the activities as distinct intrusion sets (and be able to merge them if it changes), to compare, but then they would share an alias.

**Comment by richard-julien** [comment]
Thanks for the explanation.
In this case where you want to keep them splitted, could be relevant to use a stix relation between the 2, like **derived-from** or **related-to** ?

**Comment by richard-julien** [comment]
Based on that maybe we have to improve the search aspect to also get in search result element that are **derivated-from** something you search for.

Like
1. Looking for ABC
2. Find ABC for intrusion set AAA because alias=ABC
3. Find BCD intrusion set because **derivated-from** ABC
