### ISSUE TITLE
It will show error if the TLP level is not granted to the user on the whole page

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1517]
## Description
Default users can only see the data with TLP:WHITE and TLP:GREEN. If there is a page with TLP:WHITE, TLP:GREEN, TLP:AMBER or TLP:RED, the default users will get error on the page.

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: OpenCTI 4.4
3. OpenCTI client: Frontend 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the page which with TLP:WHITE and TLP:GREEN and TLP:AMBER (the default user can only see TLP:WHITE and TLP:GREEN)
2. The whole page will show error because the TLP:AMBER (or TLP:RED) can't be access for the default user

## Expected Output

Show the TLP:GREEN and TLP:WHITE data to the default user, instead of showing error.

## Actual Output

It will show error:
![image](https://user-images.githubusercontent.com/10161931/128957003-113e78f8-12c1-4f16-8be2-4b7de17c1c7a.png)

 
## Additional information
The page with TLP:GREEN, TLP:WHITE and TLP:AMBER just like:
![image](https://user-images.githubusercontent.com/10161931/128956682-799d1774-da1a-4315-851c-53fdd7d71b90.png)

If only grant TLP:GREEN and TLP:WHITE to default user, then default user will get error on the whole page (because the page has TLP:AMBER data).

**Comment by SamuelHassine** [comment]
Hello,

It seems to be linked to the permissions but the problem is not so simple. Can you please open the browser console and copy/paste the error you have in it when displaying the page and having the error?

You confirm the error in on the reports list page?

Thanks!

Kind regards,
Samuel

**Comment by MrSigmaX** [comment]
Hi Samuel:
For the error in browser console, it shows WebSocket connection to 'wss://opencti.com/graphql' failed
I think this is because that the authority of user is not synchronized with the graphql querying data with TLP:AMBER.

Hence, the user can see the entries of the report in Malware list (In this page, the TLP:AMBER is not displayed and the entry itself is not TLP:AMBER).
However, when the user clicks in the entries where TLP:AMBER ins contained, the graphql disabled the connection of the user since he does not have the authority for viewing AMBER data.
This might cause the user confused when dealing with data.

Is it possible to hide the data with TLP:AMBER inside the Malware page given the malware itself is not TLP:AMBER? (For the user who does not have the access for TLP:AMBER data)
Looking forward to your response
Thank you!

**Comment by tanyawang1218** [comment]
Hi @SamuelHassine,

As @MrSigmaX mentioned above, how do you think?
Thanks.

Regards,
Tanya

**Comment by SamuelHassine** [comment]
Hello,

@tanyawang1218 @MrSigmaX You should have something in the console when throwing Red alert on the frontend. We need the uncaught error.

Thanks a lot.

Kind regards,
Samuel

**Comment by MrSigmaX** [comment]
![image](https://user-images.githubusercontent.com/48907694/130911984-0980e977-013f-40bc-acec-2b124416d7b5.png)
Does the figure help? This is the uncaught error in the frontend console

**Comment by tanyawang1218** [comment]
HI @SamuelHassine ,

Sigma provided the log, do you have any idea?

**Comment by richard-julien** [comment]
Hi, please provide the log on the api side (opencti.log) thanks

**Comment by MrSigmaX** [comment]
Hi, the following screenshot is the error message caught from opencti.log regarding to the read_error:
![image](https://user-images.githubusercontent.com/48907694/131980149-d205d00a-6445-4e5d-900b-28abd0a7bf66.png)

**Comment by tanyawang1218** [comment]
Hi @richard-julien and @SamuelHassine,
Do you have any comments? Thank you in advance.

**Comment by richard-julien** [comment]
Reproduced on 5.0, will be fixed in the next release

**Comment by tanyawang1218** [comment]
Hi @richard-julien  and @SamuelHassine,

Got it. Thank you for the support.
