### ISSUE TITLE
V5 : Error with the export dark without background

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1630]
## Description

When selecting exports (for PNG and PDF) as "dark with not background", the image is white, and therefore the text, which is also white, is not visible. 

## Environment

2. OpenCTI version 5.0.1
3. OpenCTI frontend

**Comment by SamuelHassine** [comment]
Hello @manonviallet,

Are you sure the background is white? I've tested several times and the background is actually transparent. Can you attach a file with the white background? Since it's "dark" theme, text will remain white, you're free to add any dark background to the image (purpose of this export).

Kind regards,
SAmuel

**Comment by manonviallet** [comment]
Hello @SamuelHassine, I just check andyou are right, there is no problem, the background is transparent. Sorry for the wrong verification on my part. Maybe it is just me (I will let you decide on this one, I am open to counter arguments :) ) but maybe having "transprent background" instead of "without background" would be clearer ?

I let this open so you can see my comment, but you can definitely close this issue :)
