### ISSUE TITLE
MISP events not importing and tags

### ISSUE THREAD

**Issue by mathurin68** [OpenCTI-Platform/opencti#227]
Hah, guess I had one more!  

I'm not getting any events in from MISP but I'm guessing it's because of the 'tags'
- MISP_TAG=OpenCTI:\ Import
- MISP_UNTAG_EVENT=true
- MISP_IMPORTED_TAG=OpenCTI:\ Imported

I have 2 main tags right now in MISP 
'isight'  and 'twitter' 

is it possible to add 
- MISP_TAG=twitter,isight
- MISP_UNTAG_EVENT=true
- MISP_IMPORTED_TAG=twitter,isight

or maybe because of this...
INFO:root:Fetching new MISP events...
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Is there a setting like this I can add to the docker-compose.yml file? 
      - MISP_verifycert=false

On the other tools I've got going into MISP there's always a setting to disable SSL. 

Thanks!

**Comment by richard-julien** [comment]
Hi @mathurin68, i dont think the connector support multiple tags for now. 
You can eventually create a specific issue to improve the connector to support list of tags. 

Waiting for that enhancement you can eventually start 2 MISP connectors.

MISP01
- MISP_TAG=twitter
- MISP_UNTAG_EVENT=false
- MISP_IMPORTED_TAG=opencti-imported

MISP02
- MISP_TAG=isight
- MISP_UNTAG_EVENT=false
- MISP_IMPORTED_TAG=opencti-imported

For the SSL warning its not a problem, I personally prefer a little warning connecting a self signed certificate instead of using an unsecure connection.

**Comment by mathurin68** [comment]
It's working!!!!

Can't tell you how impressed I am with this. 

I'll hit you guys tomorrow with why I lose everything everything on restarts and all the messages disappear.  I.E. if the server restarts or if I have to stop docker-compose and restart it I lose everything. 

Can't believe this is opensource, pretty amazing.
