### ISSUE TITLE
Docker images isn't working

### ISSUE THREAD

**Issue by cybert79** [OpenCTI-Platform/opencti#233]
Hi,

I installed an Ubuntu 18.04 and updated it.
I installed docker-compose.
I followed the documentation and I keep getting this error:
if (!_validator.default.isUUID(adminToken)) throw new Error('Admin setup > Token must be a valid UUID'); // Initialize the admin account
opencti_1            |                                               ^
opencti_1            |
opencti_1            | Error: Admin setup > Token must be a valid UUID
opencti_1            |     at Object.<anonymous> (/opt/opencti/dist/config/security.js:41:53)
opencti_1            |     at Module._compile (internal/modules/cjs/loader.js:816:30)
opencti_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
opencti_1            |     at Module.load (internal/modules/cjs/loader.js:685:32)
opencti_1            |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
opencti_1            |     at Module.require (internal/modules/cjs/loader.js:723:19)
opencti_1            |     at require (internal/modules/cjs/helpers.js:14:16)
opencti_1            |     at Object.<anonymous> (/opt/opencti/dist/server.js:44:41)
opencti_1            |     at Module._compile (internal/modules/cjs/loader.js:816:30)
opencti_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
opencti_1            |     at Module.load (internal/modules/cjs/loader.js:685:32)
opencti_1            |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
opencti_1            |     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
opencti_1            |     at internal/main/run_main_module.js:21:11

Did you guys tested recently the run? I have an impression it is outdated (your documentation)

**Comment by richard-julien** [comment]
Hi @cybert79, do you follow the 'configure the environment' part? At the beginning we mention that you need to configure the APP__ADMIN__TOKEN variable with a valid UUID (https://www.uuidgenerator.net/). If this var is not well configured, an error will occured at startup. `Token must be a valid UUID`

For worker error (https://github.com/OpenCTI-Platform/opencti/issues/234), you need to configure this UUID in the appropriate configuration, aka OPENCTI_TOKEN.

**Comment by cybert79** [comment]
Ok, it works, but you should mention this in the documentation and not in the readme file :)

**Comment by richard-julien** [comment]
Hi @cybert79, Im a bit confused because its clearly mention in https://opencti-platform.github.io/docs/installation/docker. Glad you make it work.

**Comment by deepakray184** [comment]
I am also getting the same error due to "Token Must be a valid UUID". 

Hi @richard-julien - I saw your above message "do you follow the 'configure the environment' part? At the beginning we mention that you need to configure the APP__ADMIN__TOKEN variable with a valid UUID (https://www.uuidgenerator.net/). If this var is not well configured, an error will occured at startup." - I updated the .env file with APP__ADMIN__TOKEN and its UUID but its still throwing the same error. Please guide me. Also, Its seems this file doesn't exists now https://opencti-platform.github.io/docs/installation/docker.

opencti-1  | {"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Token must be a valid UUID","name":"CONFIGURATION_ERROR","stack":"GraphQLError: **Token must be a valid UUID\n**    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:75:53)\n    at initializeAdminUser (/opt/opencti/build/src/config/providers.js:45:15)\n    at platformInit (/opt/opencti/build/src/initialization.js:121:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:29:7)"}],"level":"error","message":"Token must be a valid UUID","source":"backend","timestamp":"2024-10-24T07:19:02.096Z","version":"6.3.6"}



![image](https://github.com/user-attachments/assets/42e1f3a1-cbb4-4d7c-b4af-f4c478fa2cf2)
