### ISSUE TITLE
Tags for reports

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#334]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

There is no tag for reports (apparently) in v2.0. It is a surprise because I was expecting the tag feature to be completely horizontal across openCTI objects

## Current Workaround

None

## Proposed Solution

Tagging reports is required

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by Benaglio** [comment]
**Current Workaround**

Select reports using some technical terms in the search bar (i.e: ransomware, spyware) that are written in the description field

**Proposed Solution**

Tagging reports is required (instead of using the report's description which it won't work in the case of having a short description without a technical term)
