### ISSUE TITLE
Add Targets relationship between two different countries

### ISSUE THREAD

**Issue by Benaglio** [OpenCTI-Platform/opencti#409]
## Description

In the "Countries/Knowledge/Threats" section, the creation of relationship between two different countries is possible but its type doesn't bring me options to choose (i.e: targets), is it possible to create "targets" relationship between two countries ? (i.e: China targets France)

## Environment

1. OS : debian buster 
2. OpenCTI version: OpenCTI 2.1.2
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. go to @IP/dashboard/entities/countries
2. select a country (i.e Afghanistan)
3. click on Knowledge/Threats section
4. create a relation by clicking on "add" button and create an entity
5. when you choose the entity type: "Country", you won't be able to select "Targets" relationship

## Expected Output

"Targets" relationship created between two different countries

## Actual Output
<img width="720" alt="Screen Shot 2020-01-15 at 11 40 32 AM" src="https://user-images.githubusercontent.com/18384388/72427364-e2023a00-378b-11ea-8365-1f588b61b2cf.png">

**Comment by SamuelHassine** [comment]
For this specific use case, please use a strategic Threat Actor such as https://demo.opencti.io/dashboard/threats/threat_actors/50a0e973-b0d0-4694-a8e1-16c36392330a.

In the OpenCTI data model, country cannot "targets" other entities, simply because if we do that, we are forced to admit that a country could be a threat, and therefore can "uses" Malware/TTP, etc. and be "indicated" by indicators, etc.
