### ISSUE TITLE
Why is there a limit of 5000 entities in a csv feed?

### ISSUE THREAD

**Issue by RegturH** [OpenCTI-Platform/opencti#4636]
## Description

Limit of 5.000 entities in csv feed. Why is there a limit on entities in a csv feed?

This is probably for performance but I would like to know if we can increase this?

## Environment

2. OpenCTI version: 5.11.2
3. OpenCTI client: front-end

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Data-> Data Sharing->CSv-feed
2. Create a feed with more than 5.000 entities
3. it will only show till 5.000

## Solution
Introduce an option to increase the size

`data_sharing:max_csv_feed_result`

**Comment by richard-julien** [comment]
The concept of the CSV feeds is have information rolling on a time period. In order to prevent some performance problem we decide to put a limit to 5000 elements on the rolling period. I recently introduced an option but it require to change also another option to make it work and it was not expected. I will rework that part to correctly handle the option soon.

**Comment by RegturH** [comment]
Hey Julien,

This is wonderful! Thank you for making this possible in the future :)

**Comment by RegturH** [comment]
@richard-julien sorry for my late response.  this has been solved. How Can I increase the csv feed limit?
