### ISSUE TITLE
.net microservice to send stix data feed to opencti

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#565]
Greetings,

I have a .net (c#) program that polls threat feed from a third-party provider. This will be converted to a "microservice" that will run daily in the backend.
I am planning on adding another feature in the program that will push the stix data to opencti.

So, should I just tell to the .net program to connect to OpenCTI's RabbitMQ and put the stix data to the Queue? Please correct me if this is the right approach.

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

Very interesting question and my answer will be valid for any kind of language. You have multiple options for your use case:

- You can send STIX2 formatted data to a queue that will be consumed by the worker. The worker is listening on all queues declared by the connectors, so you have to [register your connector](https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/connector/opencti_connector_helper.py#L189) to the platform (I will write a specific documentation about this for you), that will create the queue, and then you can send you data in it and the worker will consume it.
- You can pass a STIX2 JSON file directly to a tiny Python script that will just take your data and execute the [import stix2 method](https://github.com/OpenCTI-Platform/client-python/blob/61371fbea9294fecd6abcbb4555a402143a05cca/pycti/utils/opencti_stix2.py#L111).
- You can also choose to not use the broker/worker architecture or the Python library and do your API queries directly to the OpenCTI platform, the Python library is just a wrapper for this API that is quiet easy to request (GraphQL endpoints in HTTP).

Please share your progress with us, we are deeply interested. Thanks!

**Comment by richard-julien** [comment]
Hi @NetEyes, like @SamuelHassine said you have a lot of options to do that. But thinking of it I dont think anything is really on point today ... :) For me the only real solution is to act like a connector. But thinking above it we doing it wrong today.

Currently connectors  fetch the configuration from the API but communicate directly with the broker that is not a good way. We have future plan to move to Kafka to cover other features and so the fact that the connectors "needs" the broker driver is not what I want.

I dont think it required a lot of work and we definitively needs to publish an API for connector to push some Stix file for injection and get some work id to be able to get some information about how its going on. It looks like the file importer connector by the way.

In detail i imagine something like that. 
* Your backend registers as a connector with mutation `RegisterConnector($input: RegisterConnectorInput)` 
* The backend ping the platform every 40 seconds with `mutation PingConnector($id: ID!, $state: String)` to tell the platform that he's still alive
* When your backend have something to import he calls `mutation ImportStixConnector($id: ID!, $input: File)` (Prefer file instead of String because of the possible size of the stix) and get a WorkID in return. **This API doesn't exists today**
* Your connector can get info about the import status using `query work(id: ID!) { jobs {...}}` (we have the concept of work and job because a work around stix2 import can lead to multiple jobs because of our capacity to split the stix2 to have chunk to process in parallel)

Obviously this API (ImportStixConnector) doesn't exists today so if you have to do it right now you can replace it with :
* Getting the rabbitMq config from the API (get config attribute from connector get id fetching)
* Pushing the message in the according queue directly

WDYT @SamuelHassine? Looks like we need that to simplify the creation of connector and future migration of the stack from rabbit to Kafka.

**Comment by SamuelHassine** [comment]
Fully agree @richard-julien we need to open an issue about the `ImportStixConnector` mutation.

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity. Feel free to re-open it if you have any other questions/issues.

**Comment by NetEyes** [comment]
Greetings,
It's been a while since my last response. Are there any consideration in adding automated import of 3rd party stix feeds for the coming version 4?
