### ISSUE TITLE
TTP Search bar

### ISSUE THREAD

**Issue by I-Iugo** [OpenCTI-Platform/opencti#573]
## Description

When you put several words in the search bar it doesn't search correctly.

## Environment

1. OS : OpenCTI demo
2. OpenCTI version: 3.0.3
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:

- Go to "Techniques/TTPs/"
- Write **Obfuscated Files or Information** in TTPs search bar

## Expected Output

You expect to be able to find exactly what you're looking for... Maybe able to write regexp or match on several words (like Firefox)

<img width="1440" alt="Capture d’écran 2020-03-17 à 14 52 08" src="https://user-images.githubusercontent.com/7288882/76863337-a48b5d00-685f-11ea-8b9c-4df10a0ff114.png">

## Actual Output

<img width="1440" alt="Capture d’écran 2020-03-17 à 14 51 48" src="https://user-images.githubusercontent.com/7288882/76863333-a2c19980-685f-11ea-83cd-18a0ed60e860.png">

**Comment by SamuelHassine** [comment]
@I-Iugo: we definitly need to enhance search syntax and we have quiet few issues about this so I let this one open. But for your use case, like on Google, you can use double quotes to match exactly the phrase you want:

`"Obfuscated Files or Information"`

Multiple results will be show because they contain "Obfuscated Files or Information" in their description.

**Comment by SamuelHassine** [comment]
Linked to #438 and #502.

**Comment by I-Iugo** [comment]
Ok sorry, thank you :)
