### ISSUE TITLE
Improve Write's / Lower Message Que

### ISSUE THREAD

**Issue by cyamal1b4** [OpenCTI-Platform/opencti#598]
## Problem to Solve

I am successfully running the platform and it's dependencies with some learning curves along the way. However, Even after spinning up a total of 9 workers I still have an ever increasing Message Que. I have been getting things through but it seems to be falling behind and growing steadily. 

## Current Workaround

I wait a day for new AVault pulses to show up as well as other updates. I haven't tracked down the source of the lag but I assume I'm not the only one. Perhaps it's normal and if so that's fine, I just want to have this deployed correctly. 

## Proposed Solution

Please let me know what I can do to speed this up. If anything. 

## Additional Information

![OCTI](https://user-images.githubusercontent.com/50558402/78365104-34314b00-7584-11ea-8f4b-52f650ea867d.PNG)

**Comment by SamuelHassine** [comment]
@Patriot1b4 can you describe your deployment ? Docker vs manual ? Capabilities (CPU/RAM/SSD ?) of your infrastructure for ElasticSearch & Grakn especially ?

**Comment by cyamal1b4** [comment]
@SamuelHassine Yes. 
I'm running it completely through docker and not docker stack. I haven't broken off grakn and ES it is running internally, I have up to 256GB of RAM and over 20 logical processors if needed as well. Its running on Hyper-V with an Ubuntu Server 18.04 LTS which is solely running the platform and its dependencies with: 32GB of RAM, 8 Cores (2 Xeon Processors w/12 cores each), and a 100-150GB of SSD space partitioned off. 

Right now (off of the top cmd of my box): its using roughly 60% of its logical allotment for CPUs and 26GBs of RAM.

**Comment by SamuelHassine** [comment]
Ok @Patriot1b4. It sounds good. The performances should not be a problem for you. For production use we highly recommand to launch Grakn on a dedicated host (physical or virtual) and to deploy a true ElasticSearch cluster (physical or virtual). The rest of the components can be run in Docker containers without any problem.

For your use case, the `write` performances are fully linked to write performances of Grakn and ElasticSearch. Even if you deploy these 2 services on separate virtual machines, it will not increase a lot your performances since your are on the same physical hypervisor. Launching 9 workers will not help as well, 2 are enough  to ensure parallelism, 3 maximum. 

For your setup, it seems that you ingest a lot of initial data (what is the initial date of ingestion for CrowdStrike and AlienVault?) As precised in the documentation, more older is the date, more messages you will have in the queue. At some point, messages number will stop to increase and your platform will be stable.

But my advice is really to launch connectors one by one. First with initial datasets (MITRE, OpenCTI, CVE), and then start AlienVault with a realistic start date (I dont think it it useful to ingest 2 years old CTI data), and after your platform is stable launch CrowdStrike, and then and then...

**Comment by SamuelHassine** [comment]
Let me know if it helps :)

**Comment by cyamal1b4** [comment]
@SamuelHassine Thank you for that info! much appreciated. I have a timestamp of Jan 01 2020 for Alienvault in the .yml configuration. Crowdstrike isn't pulling.. no subscription. If it will just take time to stabilize that's fine. I do, however, have my own MISP instance I'm wanting to point to OCTI but maybe wait on that. I will try now to recycle this in that way, one by one. Thank you!

**Comment by cyamal1b4** [comment]
@SamuelHassine Its working swimmingly now. Thank you!
