### ISSUE TITLE
Date Management

### ISSUE THREAD

**Issue by nathmo** [OpenCTI-Platform/opencti#738]
## Problem to Solve
Limit error when displaying and entering date into the system

## Current Workaround
For now we just stick to the MM/DD/YYYY format and hope nobody does a mistake

## Proposed Solution

use the format 18 may 2019 instead of 05/18/2019

**Comment by richard-julien** [comment]
You want to be able to specify your picker date format for the entire platform?

**Comment by nathmo** [comment]
yes thats a neat solution too

**Comment by 8hur** [comment]
I have the same issue but I would prefer a different solution:

Since the Knowledge tab uses the ISO 8601 format, why not use this format when presenting dates?
At least allows us to use this format in the settings, English is often used as a common language and not everyone is familiar with the MM/DD/YYYY format (used only in the USA).
