### ISSUE TITLE
Clarification on how to use observables

### ISSUE THREAD

**Issue by certrik** [OpenCTI-Platform/opencti#768]
I need some clarification on how to use observables. 
If I add a new observable by hand I can also generate an indicator of it and link this indicator to other stuff.
If I automatically import observables from a pdf, I cannot generate indicators from them. How should they be used, if I cannot use them as indicators?
Also it would be great if classification (e.g. TLP:AMBER) could be set as bulk operation. If I import observables from a document which itself is TLP:AMBER it is just a hassle if I have to indicate classification for each observable individually.

**Comment by richard-julien** [comment]
@SamuelHassine can you answer that? thanks

**Comment by SamuelHassine** [comment]
Hello @certrik,

A few answers:

1. You can create indicators from observables imported from a PDF, please check the PDF connector settings (ie. create_indicator: True/false).
2.  Now, observables will have the same classification as the report containing it.

In general, V4 will bring a lot more features on observables as well as a clearer use cases for them, because they will be fully modelized, linkable to any other entity or observables.

Kind regards,
Samuel
