### ISSUE TITLE
Incomplete list when adding a relationship

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#806]
# Description

When adding a relation  between 2 entities, the list of proposed items is not complete and you have to go through the search field.
TTP, Sector, Malwares, ...

# Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.2.2
	3. OpenCTI client: Platform
	
# Reproducible Steps

Create relation in Reports/<Report name>/Knowledge

# Expected Output

Have all items by category in the list

# Actual Output 

Missing the desired item in the list

**Comment by manonviallet** [comment]
Not sure this is really possible or desirable to implement, to discuss.

**Comment by SamuelHassine** [comment]
Hello @manonviallet,

We are not able to implement this one. Some users can have more that 1 millions entities in their platform, definitely not a good idea to display everything. 

Currently, we display 100 entities, ordered by creation date. So in general you find immediately what you are looking for. But it is not possible to display more by default, because of potential browser performances issues.

Kind regards,
Samuel
