### ISSUE TITLE
Prohibit Indicator relation indicates TTP

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#878]
## Problem to Solve
 
Indeed, in the April OpenCTI presentation the relationship: "Indicator indicates the TTP" is to be banned. However, in OpenCTI this relationship is possible.

The correct relationship is "Indicator indicates the relationship of the TTP" and not the TTP directly

## Current Workaround

None 

## Proposed Solution

Prohibit direct relation: Indicator indicates TTP

## Additional Information

![IMAGE6](https://user-images.githubusercontent.com/38727361/95612973-7d4ae600-0a64-11eb-8465-732892c2243d.PNG)

**Comment by SamuelHassine** [comment]
Hello @amr-cossi,

The use case showed in the presentation is important because "maliciouslink.com" is clearly related to a specific "implementation" of the attack pattern "Spearphishing link" by APT28. Nevertheless, there are a lot of indicators and signatures on the field that are indicating an attack pattern in general (generic Sigma rules, generic Tanium Signals, etc.). 

So the relationship Indicator => indicates => Attack pattern is completely valid in this case, as well as Indicator => indicates => Vulnerability. Additionally this kind of relationship is part of the STIX 2.1 standard.
