### ISSUE TITLE
Provide tutorials and workshops

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#998]
Greetings,

Newbie here .. please provide tutorials/workshops for Administrator and Users.
For Administrator workshop like ...
- Maintenance, Updates and Migration
- Creating and Using Connectors
-

For CTI Users like ..
- General Use .. go through phases of threat intelligence lifecycle
- Curating IoCs
- Pushing to bad IPs to NGFW
- Pushing IoC to SIEMS

Would be great if you guys provide hands-on workshop.

**Comment by dmille6** [comment]
i'd also like 2nd these kinds of tutorials.. also one maybe on setting up and performance tuning for a production environment.

**Comment by manonviallet** [comment]
Good afternoon @NetEyes 
This issue is taken into account, and we are working towards offering more content and support through the documentation (https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518), blog posts (https://medium.com/luatix). Workshops and other contents are also on the roadmap.
As a result, I will close this issue. Don't hesitate to join the slack channel so you are updated on new content, and to open an issue if you find that you have another question.
Cheers, Manon
